### ISSUE TITLE
installation: instructions for installing docco lack necessary flag?

### ISSUE THREAD

**Issue by cwulfman** [ion-oset/cast-vote-records#1]
the current instructions say    

`npm --install docco`;

on my system, at least (macos 10.15.7, npm 6.13.4) the `-g` flag is required:

`npm install -g docco`

**Comment by ion-oset** [comment]
Local installs are preferable for projects. You shouldn't need to globally install a command.

But you _do_ need the `package.json` for `npm install` (no package) to work, and that wasn't checked in. Should be fixed.
