### ISSUE TITLE
Build a CVR compiler (see issue #15) A bare-bones data format and one or more XSL stylesheets that expand the bare-bones data into fully-fledged CVR documents.

### ISSUE THREAD

**Issue by cwulfman** [ion-oset/cast-vote-records#17]
(see issue #15) A bare-bones data format and one or more XSL stylesheets that expand the bare-bones data into fully-fledged CVR documents.

**Comment by ion-oset** [comment]
Implementation has moved to https://github.com/cwulfman/election-definer.
All follow ups should go there.
