### ISSUE TITLE
BallotStudio generates coordinates for drawing ovals; contains code for drawing ovals

### ISSUE THREAD

**Issue by cwulfman** [ion-oset/cast-vote-records#3]
In the BallotStudio app, one can see a json-formatted set of "bubbles", which appear to be coordinates.

The Choice class includes a draw method:
https://github.com/TrustTheVote-Project/BallotStudio/blob/8bdb5e9093e92e4bb71d24209f4fcc2ca61f8056/draw/draw.py#L118

The InstructionsHeader class also knows how to draw a bubble:
https://github.com/TrustTheVote-Project/BallotStudio/blob/8bdb5e9093e92e4bb71d24209f4fcc2ca61f8056/draw/draw.py#L650

**Comment by ion-oset** [comment]
Yes. Those are what I mentioned, somewhat hand-wavingly, in our meeting.

Did you mean to file this here as an issue or as a note? If the latter, would you add it to the wiki instead?

**Comment by cwulfman** [comment]
Done
