### ISSUE TITLE
Create Gadget County ballot statement text

### ISSUE THREAD

**Issue by ion-oset** [ion-oset/cast-vote-records#9]
Come up with a Gadget County ballot statement, while recognizing that each state's template is going to have their own wording.

Here is the San Mateo form to give you an idea of type of eye candy to use at top and bottom, to show that we can have a state-specific template that incorporates typical eye candy and also has all the data required. The military/overseas address is not relevant to our case; and while name address and signature are required, other fields are required in our case.

> "Oath of Voter
>
> I _____ _____ do swear and affirm that: I am a registered voter of Gadget County; I am qualified to vote in this election; I have not applied, and do not intend to apply for an absentee ballot in any other jurisdiction in this election; I have truthfully provided my name, signature and other personal information to be used to determine my voter qualification and the eligibility of my absentee ballot to be counted. I understand that such name, signature, and personal information will be separated from my voted ballot to maintain its anonymity at the onset of the ballot tabulation process and thereafter. My last known Gadget County address is: "

This would then be followed by these sections:

- Two blanks are first name and last name (no need for
prompts under the line).
- Underline fields for:
    - Street Address (half page width)
    - Apt/Unit (maybe 8 chars)
    - City the rest of the line width except for 5 chars)
    - ZIP (5 chars)
- After that:
    - "Driver's License or State ID Card Number" (20 char field)
    - "Social SecurityNumber" (10 char field)
- Below that line, we need a line with 2 checkboxes:
    1. "I do not have a Driver's License or State ID Card Number"
    2. "I do not have a Social Security Number"

    The checkboxes need to be aligned with the text on the previous line.

- Horizontal space to insert a photo of a front/back of a driver's license.

    You can use images from https://dps.mn.gov (found by searching "sample minnesota driver's license back side") placed beside one another.
- More boilerplate:

    > "I declare under penalty of perjury under the laws of the State of The Future that the foregoing declarations are, to the best of my knowledge and belief, true and correct."

- A line with a half-line-width field for "Signature of Voter" and half line for date.
- A line with a half-line-width field for "Signature of Witness" and half line for "Name of Witness"

    Any kind of scrawlish image will do for the signatures.

- After that any vertical space remaining
- Finally a footer with address phone fax email web similar to San Mateo.

Separately a 12-digit 1-D barcode (linear code), exact position to be determined.

**Comment by cwulfman** [comment]
@trustthevote also added:

>Arrrg! I also forgot the barcode. Just a typical 1-D barcode (linear code) for 12 digits. I'll leave it to you to put it someplace not too ugly.

>FWIW, processing of this form requires data entry to look up the voter in the VR system. Instead of DLNs and whatnot, this form can include the voter's unique voter record ID, so that the look up just uses a scan wand and no typing. (The voter doesn't enter this; the app gets it from the back end, and puts it on the form for the voter).

**Comment by ion-oset** [comment]
Closed by #13
